### PR TITLE
Docker: Switch to ruby:X.Y-alpine base image

### PR DESCRIPTION
**Pull request by sirux88**
## Description
This PR switches the docker images to ruby-alpine based images as mentioned here: https://github.com/pglombardo/PasswordPusher/pull/714#issuecomment-1399476998

Docker image sizes will be cut by about 35% in respect to current images
image

I would suggest to give the current images some time to see if there are any issue since they had a major update in #714 

[New Base Image](https://hub.docker.com/layers/library/ruby/3.2-alpine/images/sha256-c85b4abfdee036bfd415af3cd2fa632037cd32293fe1eb8478cd8934aa9558b5?context=explore)
## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [x] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've written tests (if applicable) for all new methods and classes that I created. (`rake test`)
- [ ] I've added documentation as necessary so users can easily use and understand this feature/fix.

### CODE REVIEW

**Comment by pglombardo** [comment]
Thanks @sirux88!  Agree - let's give it a week or so and lets the current changes settle.

**Comment by MindTooth** [comment]
Maybe https://github.com/slimtoolkit/slim is also a fit to decrease the image size?  I need to test this myself more, but is something to consider. :smile:

Also, with APT and now APK, you can choose to remove the cache when running `apk add` by adding `--no-cache`.  This should remove some leftovers that's not needed for running the container.

---

For APT, the following should have been at the end:
```diff
  RUN apt-get update \
      && apt-get upgrade -y --assume-yes \
-     && apt-get install -y --assume-yes tzdata bash nodejs
+     && apt-get install -y --assume-yes tzdata bash nodejs \
+     && rm -rf /var/lib/apt/lists/*
```

**Comment by sirux88** [comment]
> Maybe https://github.com/slimtoolkit/slim is also a fit to decrease the image size? I need to test this myself more, but is something to consider. 😄
I'll look into that at the weekend.





> Also, with APT and now APK, you can choose to remove the cache when running `apk add` by adding `--no-cache`. This should remove some leftovers that's not needed for running the container.

This is indeed a valid point. I'll test that aswell

**Comment by sirux88** [comment]
> > Also, with APT and now APK, you can choose to remove the cache when running `apk add` by adding `--no-cache`. This should remove some leftovers that's not needed for running the container.
> 
> This is indeed a valid point. I'll test that aswell

I added the '--no-cache' option. This resulted in:
image
Removing about 30MB and which means a cut of 43% in respect to current master images

**Comment by sirux88** [comment]
> > Maybe https://github.com/slimtoolkit/slim is also a fit to decrease the image size? I need to test this myself more, but is something to consider. 😄
> 
> I'll look into that at the weekend.

@MindTooth 
I tried that but I'm struggeling a bit with getting this to work. The build process get interrupted within starting the embedded puma webserver. I tried with `slim build --target pwpush-ephemeral-alpine -tag pwpush-ephemeral-alpine-slim`
Did you make any progress on that?

**Comment by MindTooth** [comment]
I'm sorry.  I've not had the time to really test this.  Struggled a bit to just getting to build images regularly.

I would image if the `Dockerfile` does some extra steps running stuff, slim will not work.  Can't say for sure, but I image it only strip stuff if you only bundle code inside the image.

I don't think testing out slim should be a stopp for this PR.  We can investigate at a later time. :)

**Comment by sirux88** [comment]
For building docker containers refer to https://github.com/pglombardo/PasswordPusher/wiki/How-to-Build-Docker-Containers-from-Source

I agree excluding `slimtoolkit` from this PR. 
Maybe we can use it for future improvements

**Comment by MindTooth** [comment]
Thanks for the link.  I did try doing locally on macOS.  I'll look into it more.

**Comment by MindTooth** [comment]
Another one. 😅

https://github.com/GoogleContainerTools/distroless

**Comment by sirux88** [comment]
> Another one. 😅
> 
> https://github.com/GoogleContainerTools/distroless

I like the other one more. This one needs changes to the base image. 
This will make things more complicated

**Comment by pglombardo** [comment]
Hi @sirux88 @MindTooth - thanks for digging on this one.  I'll test this out and aim to merge by this weekend.

**Comment by pglombardo** [comment]
Just tested all three containers locally and no issues.  <250MB containers are very slick.  Let's keep these links to the other toolsets for potentially sometime in the future.

Thanks again!

**Comment by pglombardo** [comment]
Released in: https://github.com/pglombardo/PasswordPusher/releases/tag/v1.26.0

**Pull request merged**
