### PR TITLE
Add option to disable the Delete link

### PR DESCRIPTION
**Pull request by pglombardo**
It would be awesome to have an option in config file to disable the delete link "Nah. I've got it. Delete it now.".
We are trying to use it with a large group and there is always someone that delete the password before the pre-determined # of views.
Thanks

### CODE REVIEW

**Comment by pglombardo** [comment]
Added a `deletable_by_viewer ` option:

pwpush deletable 2016-02-15 at 0 11 02

And even that option will be optionally visible/functional with the global settings.  e.g. You can modify global config to disallow password deletion entirely and not show that checkbox:

```
# Are un-expired passwords deletable by viewers?
DELETABLE_BY_VIEWER_DEFAULT = true
# Offer passwords to optionally be deletable/undeletable?
SHOW_DELETABLE_OPTION = true
```

... in [config/environment.rb](https://github.com/pglombardo/PasswordPusher/blob/per-password-options/config/environment.rb#L20-L23)

**Comment by alexandrezia** [comment]
Awesome, Thanks !

I'm trying to deploy this change but no luck

Using branch: **per-password-options**

```
export RAILS_ENV=private
```
```
bundle install --without development production test --deployment
-> success
```
```
bundle exec rake db:setup
-> success
```
Then the following command fails:
```
bundle exec rake assets:precompile
/usr/local/rvm/rubies/ruby-2.1.5/bin/ruby /var/www/htdocs/pwpush/vendor/bundle/ruby/2.1.0/bin/rake assets:precompile:all RAILS_ENV=private RAILS_GROUPS=assets
rake aborted!
ExecJS::ProgramError: Unexpected token: operator (<) (line: 12817, col: 29, pos: 400103)

Error
    at new JS_Parse_Error (<eval>:2659:11936)
    at js_error (<eval>:2659:12155)
    at croak (<eval>:2659:20622)
    at token_error (<eval>:2659:20759)
    at unexpected (<eval>:2659:20847)
    at expr_atom (<eval>:2659:29141)
    at maybe_unary (<eval>:2659:31652)
    at expr_ops (<eval>:2660:404)
    at maybe_conditional (<eval>:2660:496)
    at maybe_assign (<eval>:2660:939)
    at maybe_assign (<eval>:2660:1113)
    at expression (<eval>:2660:1252)
    at simple_statement (<eval>:2659:24162)
    at <eval>:2659:22152
    at <eval>:2659:21493
  (in /var/www/htdocs/pwpush/app/assets/javascripts/application.js)new JS_Parse_Error ((execjs):2659:11936)
js_error ((execjs):2659:12155)
```

**Comment by alexandrezia** [comment]
The issue is in file
```
app/assets/javascripts/passwords.js
line 57
```

[passwords.js](https://github.com/pglombardo/PasswordPusher/blob/per-password-options/app/assets/javascripts/passwords.js#L57)

Specifically this string: 
```
<%=DELETABLE_BY_VIEWER_DEFAULT%>
```

**Comment by alexandrezia** [comment]
If I edit file:
config/environments/private.rb
and change
```
config.assets.compress = true
```
To
```
config.assets.compress = false
```

Than, It works.

**Comment by pglombardo** [comment]
Gah thanks for testing and finding that!  I'm seeing that locally too.  I think I need to have password.js pre processed as an erb template before asset compilation.  I'll take a look at this soon.

**Comment by pglombardo** [comment]
@alexandrezia How are you doing with this branch?  Are you using it?  I'm going to finish it up hopefully soon and merge it in for the main site.  I'd also like to add a few more per password options such as "Disable password display blur" which sometimes doesn't work well on mobile devices.

In any case, I hope you are finding this useful.

**Comment by alexandrezia** [comment]
Hi,

 Yes I'm using this branch, however I had to edit the problematic .js file
and fix it mannualy,
  It's working real good.
  The option to remove the blur would be awesome.

  If I may give you a suggestion, my users tend to select the password with
the mouse and then Control+C / Option+C to copy it, and some of them were
complaining that the selection does not shows correctly (I know it is only
the CSS that does not display the gray box arround the password),
 Perhaps you could add an option to use a traditional gray select box
arround the password when selecting it, so it will be more intuitive for
users

Thanks for this great app, and thanks for the feedback.

Alexandre

**Comment by pglombardo** [comment]
Excellent to hear.  I have a fix planned for the .js file so that work around won't be needed.

Great suggestion on the password highlighting as well.  I agree. #34

**Comment by pglombardo** [comment]
This PR is still slated to be merged once I get back from vacation.

**Pull request merged**
