### PR TITLE
Docker: fix broken docker arm builds

### PR DESCRIPTION
**Pull request by sirux88**
## Description
Since #768 got merged docker images don't get built.
This is due to ARM images don't get built. x86_x64 images are fine.
It seems alpine-ARM-base images miss some references needed for successfull building.

This draft fixes:
- `mysql builds `(by adding libc6-compat)
- `postgres builds` (by adding libc6-compat)
- `partially ephemeral builds` (by adding libc6-compat)

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [X] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've written tests (if applicable) for all new methods and classes that I created. (`rake test`)
- [ ] I've added documentation as necessary so users can easily use and understand this feature/fix.

### CODE REVIEW

**Comment by sirux88** [comment]
@pglombardo
I'm abroad a couple of days. I'll try to fix this by the end of the week.

If you want to fix this by yourself in between feel free to use this draft.
It seems there's some problem with native sqlite libs on ARM.
Mysql and postgres should work fine.

Nevertheless I suggest reverting #768 to get docker builds back functional as long as this isn't fixed.

**Comment by pglombardo** [comment]
Hi @sirux88 - thanks for pointing this out.  I think this can wait until you get back.  `release` is still stable and available...

Have a good trip!

**Comment by pglombardo** [comment]
Tried arm build locally with `docker buildx build --platform linux/arm64 -t pglombardo/pwpush-postgres:armfix .` all went wel.  Gonna merge to try out the Github builds.  Thanks @sirux88!

**Comment by sirux88** [comment]
I'd appreciate if builds are fine.

Since I tried the same a couple days ago it would be weird if it's working now.

But let's see

**Comment by pglombardo** [comment]
postgres built for me without issue.  Tried ephemeral and it died related to sqlite3 like you mentioned....  Wondering if it's just local Mac issue.   I'll see if I can resolve as I get bits of time.

**Comment by sirux88** [comment]
Yeah postgres and mysql are fine. 

But SQLite is broken on my arm development system (no Mac) as well. And this issue is tied to on Alpine base images only. Old buster slim images are ok 

Since I'm back from my trip I'll try to resolve the issue tomorrow (or at least on Friday)

**Comment by sirux88** [comment]
It seems that the not working SQlite3 gem on alpine is a known issue https://github.com/sparklemotion/sqlite3-ruby/issues/372
It could as well be by design as https://github.com/sparklemotion/sqlite3-ruby says that `aarch64-linux (requires: glibc >= 2.29)`. Since alpine uses musl and not glibc this may be the problem.

Additionally it's stated how to avoid the precompiled gem https://github.com/sparklemotion/sqlite3-ruby#avoiding-the-precompiled-native-gem and build them by source

To archieve that it is necessary to add some stuff to the `Gemfile` (and `Gemfile.lock`) since it didn't work out of the box.

Now the sqlite gem should be build by source and platform specific.

@pglombardo 
Sorry for this wall of text but I think it could be usefull in some time in the future. 
I would appeciate if you could evaluate what if've done from the ruby point of view since my ruby skills are very limited.
I'll try to let the containers built on github tomorrow but it seems that everything will work out well.

**Comment by pglombardo** [comment]
New containers are building: https://github.com/pglombardo/PasswordPusher/actions/runs/4206484249

**Comment by pglombardo** [comment]
Builds successful and the ephemeral container is working perfectly.  Thanks for fixing @sirux88!

**Pull request merged**
