### PR TITLE
Removing dependency on Flash

### PR DESCRIPTION
**Pull request by pyro2927**
Adobe has stated that [Flash will no longer be supported in 2020](https://arstechnica.com/information-technology/2017/07/with-html5-webgl-javascript-ascendant-adobe-to-cease-flash-dev-at-end-of-2020/).  It is also disabled by default in Chrome, will not be shipping with Firefox, and in general is closing in on its EoL.

2017-10-16 at 10 07 pm

This PR adds in [clipboard.js](https://clipboardjs.com/) in order to handle copying text to the clipboard.  I am not a frontend person, so my UI changes may not be optimal 😕

### CODE REVIEW

**Comment by pglombardo** [comment]
I love this.  This is a great PR.  I'll test a a bit and will merge soon.

**Comment by pglombardo** [comment]
@pyro2927 could you also remove the app helper and the .swf assets?  Thanks

https://github.com/pglombardo/PasswordPusher/tree/master/app/assets/flash
https://github.com/pglombardo/PasswordPusher/blob/master/app/helpers/application_helper.rb#L2-L30

**Comment by pyro2927** [comment]
At work right now but I can do this later tonight when I'm home!

**Comment by pglombardo** [comment]
Thanks @pyro2927!  Merging and will deploy to pwpush.com over the weekend.

**Pull request merged**
