### PR TITLE
Change to use docker metadata action for tags

### PR DESCRIPTION
**Pull request by MindTooth**
## Description

Change to use the upstream [Docker Metadata action](https://github.com/marketplace/actions/docker-metadata-action) for populating the tags.  The old action is obsolete.

I've commented out the workflow_dispatch section as to ask how it's used in the real world.  Is it something that we can tweak using the upstream action?

Ed1t: my goal was to have these in the image:
```json
    "Labels": {
        "maintainer": "pglombardo@hey.com",
        "org.opencontainers.image.created": "2023-06-27T17:27:21.882Z",
        "org.opencontainers.image.description": "🔐   An application to securely communicate passwords over the web.  Passwords automatically expire after a certain number of views and/or time has passed.  Track who, what and when.",
        "org.opencontainers.image.licenses": "Apache-2.0",
        "org.opencontainers.image.revision": "59c9bed0ca6acc1f293bbfca28f92decc5cd5cbb",
        "org.opencontainers.image.source": "https://github.com/MindTooth/PasswordPusher",
        "org.opencontainers.image.title": "PasswordPusher",
        "org.opencontainers.image.url": "https://github.com/MindTooth/PasswordPusher",
        "org.opencontainers.image.version": "latest"
    },
```

Especially `org.opencontainers.image.source` so that Renovate are able to pull in a changelog.  Without it, Renovate isn't able to pull a changelog, nor link to the package name.

### Missing link and changelog

Screenshot 2023-06-28 at 11 44 41

https://github.com/MindTooth/renovate-docker-test/pull/3

### Link and changelog

Screenshot 2023-06-28 at 11 52 21

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've written tests (if applicable) for all new methods and classes that I created. (`rake test`)
- [ ] I've added documentation as necessary so users can easily use and understand this feature/fix.

### CODE REVIEW

**Comment by MindTooth** [comment]
I tried out caching and it speed up the job from 45 min to 25 s. 🤣

**Comment by pglombardo** [comment]
This looks great @MindTooth.  I'm traveling for the next few weeks so I might not get to merge this until I'm back.  July 21 or so.

**Comment by MindTooth** [comment]
@pglombardo let me know what you need.  I'm happy to answer questions.  I'll have another look at it again tomorrow to see if I can make some more improvememts.

What I want to know is what your ideal workflow is.  I'm big fan of automation. 😄

**Comment by pglombardo** [comment]
I agree - I think this is a good addition.  I'm all for adding the tags and supporting Renovate.  I just saw that Renovate opened 700k PRs against all OSS repos on Github 😮 

I'll revisit this soon.

**Comment by pglombardo** [comment]
@MindTooth do you want to make any more changes here?  I'm willing to merge and try out the updated builds when you're ready.

**Comment by MindTooth** [comment]
> @MindTooth do you want to make any more changes here? I'm willing to merge and try out the updated builds when you're ready.

Give me tonight. 😄  At work now, but have some time later today.  

One thing I wanted to look at was if "docker/metadata-action@v4" could perhaps act as `DOCKER_PUSH`.  So long as it's a valid tag, we push an image (bool).

Also, maybe remove the long commented out code.  It's still in this PR.

**Comment by pglombardo** [comment]
> One thing I wanted to look at was if "docker/metadata-action@v4" could perhaps act as DOCKER_PUSH. So long as it's a valid tag, we push an image (bool).

I believe we're not even using DOCKER_PUSH (it's always true) and instead only trigger the entire workflow with the `on->push->tags` event.  So I think we can assume push==true if valid tag.

> Also, maybe remove the long commented out code. It's still in this PR.

Agree - remove it so we'll have a clean PR.

**Comment by MindTooth** [comment]
Removed `DOCKER_PUSH` and the comment.

**Comment by pglombardo** [comment]
ok merging and I'll push a new tag to test the docker builds

**Comment by MindTooth** [comment]
> ok merging and I'll push a new tag to test the docker builds

I'm near the computer and available for debugging.

**Comment by pglombardo** [comment]
New containers building now: https://github.com/pglombardo/PasswordPusher/actions/runs/5737816968

**Comment by MindTooth** [comment]
Screenshot 2023-08-02 at 12 46 15

This was what I wanted to see. 😄  Though, I've not encountered that warning. 🤔   I'll monitor it and see if I can find out why.

**Comment by MindTooth** [comment]
Ah.  I think it's because you have `v` in front and `{semver}` does not use it.

https://github.com/marketplace/actions/docker-metadata-action#basic

Let's see if it's a problem.  I can provide a fix later.  Since it seems to be able to create correct tags anyway.

**Comment by MindTooth** [comment]
Ah.  Seems like pushing was disabled. 😭 

https://github.com/pglombardo/PasswordPusher/actions/runs/5737816968/job/15550170912

**Comment by MindTooth** [comment]
> Ah. Seems like pushing was disabled. 😭
> 
> https://github.com/pglombardo/PasswordPusher/actions/runs/5737816968/job/15550170912

FIx: https://github.com/pglombardo/PasswordPusher/pull/1312

**Comment by pglombardo** [comment]
Nice thanks for digging.

**Pull request merged**
