### PR TITLE
Unify Gemfiles using bundle groups

### PR DESCRIPTION
**Pull request by sirux88**
## Description
`Gemfile` (and Gemfile.lock) in root directory and `Gemfile` (and Gemfile.lock) in .\gemfiles\mysql only differ in its used database gem (`gem pg` and `gem mysql2`) within production group.

Therefore I added an optional group `driverpg` and `drivermysql` within the root Gemfile and dropped the unnecessary mysql-Gemfile.

These optional group can be used via `bundle config set with 'driverpg'` or `bundle config set with 'drivermysql'`.

Additionally I updated the corresponding Dockerfiles.

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [x] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've written tests (if applicable) for all new methods and classes that I created. (`rake test`)
- [ ] I've added documentation as necessary so users can easily use and understand this feature/fix.

### CODE REVIEW

**Comment by pglombardo** [comment]
Nice idea!  Could you rename `driverpg` and `drivermysql` to the simpler `postgres` and `mysql` to mirror the container images?

This could be a good mode to swap or add in new backends quickly.  👍

**Comment by sirux88** [comment]
> Nice idea! Could you rename `driverpg` and `drivermysql` to the simpler `postgres` and `mysql` to mirror the container images?

Done

> This could be a good mode to swap or add in new backends quickly. 👍

yeah I thought this aswell. 

I tried to mirror these change into https://github.com/pglombardo/PasswordPusher/blob/539824b779af2fa4631069d617190adbccd3ea0b/config/database.yml. 
In my opinion there should be a section containing `postgres` (the group from the Gemfile) with `adapter: pg` 
But I couldn't manage to get this working. I'm not that skilled ruby programmer.

Benefit would be that building the docker containers wouldn't require environment setting variable "DATABASE_URL" that early.
Seems rails uses that variable to determine which adapter to use for compiling and running. 

Maybe you could look at that @pglombardo. It would bring you're proposal further I think

**Comment by sirux88** [comment]
> I tried to mirror these change into https://github.com/pglombardo/PasswordPusher/blob/539824b779af2fa4631069d617190adbccd3ea0b/config/database.yml. In my opinion there should be a section containing `postgres` (the group from the Gemfile) with `adapter: pg` But I couldn't manage to get this working. I'm not that skilled ruby programmer.
> 
> Benefit would be that building the docker containers wouldn't require environment setting variable "DATABASE_URL" that early. Seems rails uses that variable to determine which adapter to use for compiling and running.

I did it the other way around since conditionals in database.yml seem complicated.
Now we can get rid of database.yml. 
Single caveat: `DATABASE_URL` has to be set for sqlite adapter each time. 
But it can be shifted from `private` to `production` environment.

If this will get accepted README.md of main page needs some correction within lines 133-140

**Comment by pglombardo** [comment]
Interesting.  I thought `database.yml` was a requirement of the framework.

The naming in the `database.yml` file (production, development, private) are a different paradigm coming from the Rails framework.  It seems like you found a work around in any case.

Give me a bit to test this out and I'll post back soon.

**Comment by sirux88** [comment]
`database.yml` isn't a forced framework requirement. 
You can setup database connections via `database.yml` file or via `DATABASE_URL` environment variable. 

See [Configuring Rails Applications chapter 3.20](https://edgeguides.rubyonrails.org/configuring.html#configuring-a-database)

**Comment by sirux88** [comment]
I just fixed to newest master changes and ruby tests fail now. 
Did they fail on my previous commit aswell? If so I didn't noticed that...

But the reason is valid. No `config\database.yml` anymore
On the other hand, is testing valid if only testing against sqlite adapter?

@pglombardo: 
Any suggestions how to handle with this? 
Revert deletion of `config\database.yml` to stay in line with testing?

**Comment by pglombardo** [comment]
Ok makes sense.  The framework requires `config/database.yml` only when `DATABASE_URL` isn't specified.  It works as a good fallback so can you re-add?

Then let me know when you're done and I'll merge.  One less Gemfile is 👍

**Comment by sirux88** [comment]
> The framework requires `config/database.yml` only when `DATABASE_URL` isn't specified.

Yes that's exacly the point

I'll re-add it on the weekend and will let you know afterwards

**Comment by pglombardo** [comment]
Could you remove [this block](https://github.com/pglombardo/PasswordPusher/blob/master/.github/dependabot.yml#L17-L26) from dependabot too so we keep the removal all together/in one PR?

**Comment by sirux88** [comment]
`config/database.yml` is back and `dependabot.yml` got updated.

But don't know why the check still fail. 
Maybe because of the removal itself? Is it referenced somewhere within the tests?

**Comment by pglombardo** [comment]
Not sure why it shows conflict when that file is deleted in the end...

I'll merge and deal with the tests on master.

**Comment by sirux88** [comment]
ok lets see

**Comment by pglombardo** [comment]
This was released in [v1.25.0](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.25.0).  Thanks for the contributions and help @sirux88!

**Pull request merged**
