### PR TITLE
refactor(dockerfile): move layers around for speed improvement

### PR DESCRIPTION
**Pull request by MindTooth**
## Description

Working #1509 was a bit too slow when the layers were in the old order.  `COPY ./ .` early in will result to always needing to build the deps.

Even updated `Gemfile.lock` to the version inside the container, again to limit the need for rebuild.

And, do we really need `ENV LC_CTYPE=UTF-8 LC_ALL=en_US.UTF-8`?  I see no docs on why.  Upstream already sets UTF-8 https://github.com/docker-library/ruby/blob/31c1fdba369192fe2c3cf327d7d98819edc1400b/3.2/alpine3.18/Dockerfile#L28

Ed1t: I also put the packages on separate lines so it's easier to see what is installed.  I personally prefer this as a way to always have control what is installed.  That way you can look for similarities, etc. for improving the container images.

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [x] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've written tests (if applicable) for all new methods and classes that I created. (`rake test`)
- [ ] I've added documentation as necessary so users can easily use and understand this feature/fix.

### CODE REVIEW

**Comment by pglombardo** [comment]
> And, do we really need ENV LC_CTYPE=UTF-8 LC_ALL=en_US.UTF-8? I see no docs on why. Upstream already sets UTF-8 https://github.com/docker-library/ruby/blob/31c1fdba369192fe2c3cf327d7d98819edc1400b/3.2/alpine3.18/Dockerfile#L28

I think we need these.  git blame leads to #912.

**Comment by MindTooth** [comment]
> > And, do we really need ENV LC_CTYPE=UTF-8 LC_ALL=en_US.UTF-8? I see no docs on why. Upstream already sets UTF-8 https://github.com/docker-library/ruby/blob/31c1fdba369192fe2c3cf327d7d98819edc1400b/3.2/alpine3.18/Dockerfile#L28
> 
> I think we need these. git blame leads to #912.

Okay.  Thanks for finding out.  I'm ready with this getting merged if you are okay with it.  Working on the disclaimer feature was a bit slow as it compiled the gems every time. 🤔

**Comment by pglombardo** [comment]
Excellent - but let me hold off for a couple days to make sure nothing blows up tomorrow (Monday) with the new universal container.  Don't think so but just to be safe...

**Comment by MindTooth** [comment]
Based on https://github.com/pglombardo/PasswordPusher/blob/1520a93c76eeb0227ded204fec2705b5871c4cf7/config/initializers/assets.rb#L8 and I might have asked this before, but is `yarn install` necessary in the build if it’s using stuff from vendor?

**Comment by pglombardo** [comment]
> and I might have asked this before, but is yarn install necessary in the build if it’s using stuff from vendor?

That step is needed unfortunately.  `rake assets:precompile` evaluates `node_modules` to compile javascript and stylesheets.  These are packaged into `public/assets` and fingerprinted.

`vendor/` only has a few remnants that we use.

**Comment by pglombardo** [comment]
Thanks @MindTooth!  Merging...

**Comment by MindTooth** [comment]
I saw you created a release for v1.32.3.  But that tag is three days old, so I'm not sure if the latest changes is actually included?

Screenshot 2023-10-13 at 11 19 59

**Comment by pglombardo** [comment]
Damn I messed up the release 🤦  - thanks for pointing it out!

**Comment by pglombardo** [comment]
ok [v1.32.4](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.32.4) is the new v1.32.3 😄 

I'm still getting used to the new release process with embedded version...

**Pull request merged**
