### PR TITLE
Add image push back

### PR DESCRIPTION
**Pull request by MindTooth**
Was unfortunately disabled with last PR.

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've written tests (if applicable) for all new methods and classes that I created. (`rake test`)
- [ ] I've added documentation as necessary so users can easily use and understand this feature/fix.

### CODE REVIEW

**Comment by MindTooth** [comment]
If caching works okay after the latest changes, maybe it's possible to add building of containers with PRs too. 🤷🏻‍♂️

**Comment by pglombardo** [comment]
Ok this is a good start - then we can expand after it's stable/working.

**Comment by MindTooth** [comment]
Compared to [this](https://github.com/MindTooth/PasswordPusher/actions/runs/5478392387/job/14835390935), things will improve after we push the cache for the first time.

**Comment by pglombardo** [comment]
Just tested the containers and they look great.  I'm going to merge another PR and kick off another build now.

**Comment by MindTooth** [comment]
From the logfile:

```
#19 [linux/amd64 build-env 7/9] RUN bundle config set without 'development production test'     && bundle config set with 'sqlite'     && bundle config set deployment 'true'     && bundle install     && yarn install
#19 0.740 Bundler 2.4.18 is running, but your lockfile was generated with 2.3.25. Installing Bundler 2.3.25 and restarting using that version.
```

Guess it triggers a rebuild anyway because the lockfile is different I guess?

**Pull request merged**
