### PR TITLE
Client-side JS encryption of passwords

### PR DESCRIPTION
**Pull request by smidgen**
This is my first time dipping my toes in ROR, so please feel free to critizize any noob mistakes.

I wasn't satisfied with security: the key that encrypts all the passwords in the database is stored in plaintext in the codebase. A malicious administrator or a hacked web host could result in passwords getting decrypted and leaked in plain text.

This pull request uses the Stanford JS encryption library to encrypt passwords client-side before sending them to the server. The key is put into the part of the URL after the #, which browsers never send to the server.

I realized the database column isn't large enough, but wasn't sure how to commit the change. I ran

<code>ALTER TABLE passwords ALTER COLUMN payload TYPE varchar(2048);</code>

on my Postgres database, after experimenting and finding that 250 4-byte UTF8 characters, encrypted, plus the extra JSON properties tacked on by SJCL, comes to 1459 bytes. I figure there must be a few extra bytes added when it's encrypted server-side, so I rounded up to 2048.

### CODE REVIEW

**Comment by pglombardo** [comment]
Hey @smidgen !  Great pull-request - thanks!  Client-side instrumentation is a very interesting proposal.  I'll take some time today to see if I can test everything out.

One question of the top of my head, will this work with pre-existing passwords?

In any case, thanks!  I'll update soon.

**Comment by smidgen** [comment]
Glad you like it! No, sorry, I didn't think of making it work with pre-existing passwords. I'll take a look when I get out of work, but I think we can just add an if condition to the Javascript decryption process.

**Comment by pglombardo** [comment]
Ok great.  Also to for database changes, you can generate a migration by running `rails g migration` which will output usage help.

I welcome any public input on this PR too as this is a fairly big change to the security model.

**Comment by smidgen** [comment]
Sorry I disappeared for a week. It should now work with pre-existing passwords, and I figured out how to commit the database change.

I also noticed that MS Outlook didn't like the = signs at the end of the URL, so I got rid of those.

**Comment by pglombardo** [comment]
Thanks @smidgen !  I'll see if I can spend some time this weekend looking at the changes.

**Comment by pglombardo** [comment]
Hi @smidgen - thanks for being patient on this PR.

Although this is a good PR, I'm forced to not accept it mainly because it doesn't add any tangible value (only adds an alternative method to do the same task) and adds some risk since I'm not familiar with the JS library and can't properly evaluate it's security.  An additional reason is that I would have trouble properly maintaining this code as JS isn't my strong suit.

The idea of client-side encryption is appealing but in this case there are too many obstacles.

One other item for future reference, Ruby on Rails uses migrations that are stored in RAILS_ROOT/db/migrations.  The `db/schema.db` file is auto-generated and doesn't affect new installations.

I hate to refuse PRs but this is one of those rare cases.  I appreciate the effort and thought you made in submitting this though!

**Comment by smidgen** [comment]
I see. Though I disagree on the security (I think an extra layer of encryption adds tangibly to the security) I understand why you'd want to avoid adding complexity to the project.

Thanks for the tip about the DB!

**Pull request closed without merging**
