### PR TITLE
Application Restyling

### PR DESCRIPTION
**Pull request by pglombardo**
This is the idea.  Feedback welcome.

Live testing site available here: https://the-road-to-style-impro-mn9kq0.herokuapp.com

Screen Shot 2021-06-11 at 11 12 24 PM

Links no moved down into a separate footer area.

2021-06-12 16 55 01 127 0 0 1 d6a476c650c7

The always unbranded password reveal page.  Note no links and branding to confuse password recipients.

2021-06-12 16 55 52 127 0 0 1 719179487d5a

- Cleanup and start of an improved design
- Redesign draft
- Assets and style updates
- Favicons; Static page updates
- Updated static pages

### CODE REVIEW

**Comment by CWempe** [comment]
This is a great improvement. 👍 

Here is my feedback:
Keep in mind I am just a simple user without any design experience. 😄 

I think this tool could be used even to send passwords to customers from the help desk.
Just a wish. I do not know if any management would allow this.

But in that case I would keep it very simple and customizable (to comply with corperate design guide lines).

image


* remove the big banner at the bottom of the creation page.
  The users (e.g. service desk) do not care about information about PasswordPusher. They just want to send a password.
  * A small link to the project and a copyright might be ok.
  * But if you want to promote your product, I cannot argue with just. :)
* **(1)** This should not be red. Red indicates it is important. But this text is maybe the most unimportand part of the site. 😉 
* **(2)** After revealing the password the tool tip should tell me a click would hide the password again.
* **(3)** Instead of a separate green button I would prefer a "copy to clipboard"-icon on the right of the password field.
  Like this: 
image
* **(5)** Maybe this needs underlining (even underlining for links seem outdated) or another way to indicate the user can click this. (like the copy button in **(3)**)
  * I also would go for a more formal text than `Nah. I've got it.`. Maybe just delete this first part.
* I think **(4)** should be highlighted in a box or something instead of underlining it. This looks like a link.
* The time left counter should be hilghlighted like on the creation page.  
  image  
  image  
But maybe just bold instead of red.
* Don't forget the dynamic dark them. 😉 
* Customization
  * Personally I would use PasswordPusher via docker.
    So I would like to add a corporate logo and change font and colors via a separate file or env variables  
   But I am not a web developer. So I do not know what is best practice.

But for hosting this for friends and family, this new design would already be good enough, I think. 👍

**Comment by pglombardo** [comment]
This is excellent feedback @CWempe.  Thank you.  I'm incorporating much of this.  I agree too that the red in the color scheme might have to go.

**Comment by CWempe** [comment]
If you got something new to show, just post some screenshots.
I am happy to give more feedback. 😎 

... and I am curious about the current look. 😄 

No pressure. Take your time. 👍

**Comment by pglombardo** [comment]
This PR is complete.  Thanks for the feedback @CWempe 

2021-07-04 20 58 08 the-road-to-style-impro-mn9kq0 herokuapp com 933ad30d10f3
2021-07-04 20 58 29 the-road-to-style-impro-mn9kq0 herokuapp com 1f0ba4370c42
2021-07-04 20 58 39 the-road-to-style-impro-mn9kq0 herokuapp com 5c78d60ad7d4

**Comment by CWempe** [comment]
Looks good.

A few notes:

1. The 404-Page has still the old design. 😉   
  https://the-road-to-style-impro-mn9kq0.herokuapp.com/p/xxxxxxx
2. I still do not like the big banner at the bottom. (But I understand if you want to advertise your product)
  However I think it is wrong that the simple start page has a scroll bar on a 1920x1080 monitor.  
  image

3. I think the buttons are to bright or saturated.  
  image  
  And the copy button could be green, I think.  
  Maybe get inspired by GitHibs buttons. 😉   
  image  
  (I like the rounder edges, too)
4. And the password view page is a little scrollable, too. Even with so few content. 🤔

**Pull request merged**
