### PR TITLE
Add Option to Require Authentication to Push Passwords

### PR DESCRIPTION
**Pull request by pglombardo**

### CODE REVIEW

**Comment by pglombardo** [comment]
With this, when logins are enabled and `Settings.allow_anonymous` is `false`, the anonymous user will be redirected to the login page when going to `/` (to push a new password).

This can be toggled with the environment variable `PWP__ALLOW_ANONYMOUS`.  Default is `true`.

This does not affect secret URL retrieval by anonymous users.

Screen Shot 2022-05-31 at 09 16 02

**Comment by pglombardo** [comment]
fixes #342

**Comment by blaine07** [comment]
Morning! I am the knucklehead that requested all this..LOL :sorry!

So, this morning I set this up. I had "PHP_ALLOW ANONYMOUS" set to "TRUE" long enough to open it and confirm account creation worked. I shut down PW Pusher change variable to "FALSE" and it's like it didn't pick up that I changed the ENV. Once changed how can I get it to 'change back" to realize I changed anonymous to false?

**Comment by pglombardo** [comment]
How did you run this - from source, docker container?

> "PHP_ALLOW ANONYMOUS"

Did you use the two underscores after `PWP`?  e.g. `PWP__ALLOW_ANONYMOUS=false`

The default value for `PHP__ALLOW_ANONYMOUS` is true - so with no environment variable set, anonymous is allowed.

**Comment by pglombardo** [comment]
To add, I've tested this in multiple places and haven't found any issues.

On the staging site, `PWP__ALLOW_ANONYMOUS=false` and you get the login page for `/`:

https://pwp-stage.herokuapp.com/

**Comment by blaine07** [comment]
Yes I did have both underscores. I am running container in Unraid; so I modified what was current template(in unraid that didn't have the email stuff and etc) for the NOT Ephemeral edition to add all the new variables. This is a brand new, today install. I had an ephemeral running but axed it and picked new install directory etc.
Screen Shot 2022-06-05 at 10 12 23 AM

**Comment by blaine07** [comment]
Also, does this tell you anything useful?
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='PasswordPusher' --net='bridge' -e TZ="America/Chicago" -e HOST_OS="Unraid" -e HOST_HOSTNAME="Tower" -e HOST_CONTAINERNAME="PasswordPusher" -e 'DATABASE_URL'='postgresql://pusher:password@IPREMOVED:5432/pwpusher' -e 'PWP__ENABLE_LOGINS'='true' -e 'PWP__ALLOW_ANONYMOUS'='false' -e 'PWP__MAIL__RAISE_DELIVERY_ERRORS'='true' -e 'PWP__MAIL__SMTP_ADDRESS'='smtp.gmail.com' -e 'PWP__MAIL__SMTP_PORT'='587' -e 'PWP__MAIL__SMTP_USER_NAME'='nottopday' -e 'PWP__MAIL__SMTP_PASSWORD'='weeeeee' -e 'PWP__MAIL__SMTP_AUTHENTICATION'='plain' -e 'PWP__MAIL__SMTP_STARTTLS'='true' -e 'PWP__MAIL__OPEN_TIMEOUT'='10' -e 'PWP__MAIL__READ_TIMEOUT'='10' -e 'PWP__HOST_DOMAIN'='*******' -e 'PWP__HOST_PROTOCOL'='https' -e 'PWP__MAIL__MAILER_SENDER'='********' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:5100]' -l net.unraid.docker.icon='https://raw.githubusercontent.com/CorneliousJD/Docker-Templates/master/icons/passwordpusher.png' -p '5107:5100/tcp' 'pglombardo/pwpush-postgres'
554403b87b048b16f7413ebc2d74553e86c9d6ed717c6f0722e906ca18f2d111

**Comment by blaine07** [comment]
It's like it isn't forwarding me to "https://domain/**en/users/sign_in**" to the end there...

**Comment by pglombardo** [comment]
Ah ok - containers haven't been updated yet.  So the fix is just hang on, I'll get new containers out soon.

I'll kick of a new build/tag tonight once the code is pushed.

**Comment by pglombardo** [comment]
Tag `v1.14.0` is building now, `latest` tag will update tonight and I'll bump `release` once I run validations.

**Comment by blaine07** [comment]
> Tag `v1.14.0` is building now, `latest` tag will update tonight and I'll bump `release` once I run validations.

All. The. Thank you! :-)

Can't wait to play with it!

You're the best!

**Comment by blaine07** [comment]
Also, is there a way to get time correct? Unraid sets timezone(as seen in my run command above)but it’s 1114AM my time and container thinks it’s 16XX

B43818D0-0852-41EE-BAC7-B433B5B16F0E

**Comment by pglombardo** [comment]
The [containers are built](https://hub.docker.com/repository/docker/pglombardo/pwpush-postgres/tags?page=1&ordering=last_updated).  `release` tag will be updated sometime tomorrow likely.

As for the timezone, it looks like I'll have to add support for changing the default (which is UTC I believe).

**Comment by blaine07** [comment]
Thank you! I’ll give it a whirl as soon as I see “updates” 🎉😀👌🏻🔥

**Comment by pglombardo** [comment]
That's excellent to hear @blaine07.  Thanks for pointing this out and the great feedback.

The `latest` tag is updated to the latest code (happens automatically every Sunday evening).

**Comment by blaine07** [comment]
It seems this may be broken recently; it doesn't seem to require me to login to push?

Allow anonymous is still set as false just above. Can you confirm it's broke? it just lets me push without logging in?

**Comment by pglombardo** [comment]
No problem at all @blaine07.  I haven't pushed any code in 2 weeks because I'm inundated with other tasks.  So nothing should have changed...

Are you still using the latest containers and the env var is set inside the container itself?

**Comment by blaine07** [comment]
> No problem at all @blaine07. I haven't pushed any code in 2 weeks because I'm inundated with other tasks. So nothing should have changed...
> 
> Are you still using the latest containers and the env var is set inside the container itself?

I got it figured out. 100% my idiocracy. My hosted url is super close to that of the public pwpush.com. Browser was sending me to you and not myself with it’s auto fill… so yeah, umm welcome to Monday 🤦🏼‍♂️

So so so sorry, nothing is wrong. Just my case is the Mondays. 

I hope you have a great week; hope things slow down for you soon. Thanks for the stellar support mate! :-)

**Pull request merged**
