### PR TITLE
Development: Commit Hooks and Lint Work

### PR DESCRIPTION
**Pull request by pglombardo**
- pre-commit configuration file
- Rubocop linter run through all files.

## Type of Change

- [x] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [x] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've written tests (if applicable) for all new methods and classes that I created. (`rake test`)
- [ ] I've added documentation as necessary so users can easily use and understand this feature/fix.

### CODE REVIEW

**Comment by MindTooth** [comment]
I'm always a sucked for https://prettier.io.  At least for JavaScript, JSON, and YAML.

**Comment by pglombardo** [comment]
That looks slick.  I went with Rubocop since I have experience and it's pretty standard for Ruby.  It got a bit out of control with ~500 files updated.  :-)

Tests pass but fingers crossed no odd bugs come up...

**Comment by MindTooth** [comment]
Just to be clear, I did not mean to suggest Prettier for Ruby. 😅  There are better tools for that.

**Comment by pglombardo** [comment]
I know - just chatting/sharing tools helps :-)

**Pull request merged**
