### PR TITLE
Docker: Switch to multistage build to reduce container size

### PR DESCRIPTION
**Pull request by sirux88**
## Description
This improves the current Dockerfile to reduce redundancies and image size.
Current state:
1) refactored all` entrypoint.sh` files and all relevant `Dockerfile`s to use a common `entrypoint.sh`
=> This is to make it easier to maintain
2) improved emphemeral Dockerfile by setting up a multistage build. 
First step is for building the app.
Second step copies the built app and set's up the image for running the app
=> This step reduces image size from ~770MB to 415MB without any obvious problems

I will improve mysql and postgres images in the same manner as soon as I'll get some feedback about what I did and if it will get merged

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [x] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've written tests (if applicable) for all new methods and classes that I created. (`rake test`)
- [ ] I've added documentation as necessary so users can easily use and understand this feature/fix.

### CODE REVIEW

**Comment by pglombardo** [comment]
Hi @sirux88 early comment while you are still working on this:

1. I merged the other PR, you'll likely have to pull and rebase.
2. I like the idea of reduced container sizes as long as it doesn't add complexity (doesn't seem so)
3. Let's keep `entrypoint.sh` separate for each container in case we have to add special steps to a particular container eventually.

One example on 3 above is that we should shuffle the encryption key on pwpush-ephemeral boot.  That's on the list but not added yet.

Thanks for the PR!

**Comment by sirux88** [comment]
Ok, I'm fine with undoing 3. it doesn't bring that much benefit anyway.
I'll rebase tomorrow and continue reducing the the size of the other two docker images I mentioned.

**Comment by sirux88** [comment]
@pglombardo:
I reverted the refactoring of `entrypoint.sh` and completed postgres and mysql Dockerfiles.

**Comment by sirux88** [comment]
@pglombardo:
Additional shrinking would be possible if moving from `ruby:3.2-slim` to `ruby:3.2-alpine` as base images.
Ephemeral would lower from 416MB to 272MB. 
I didn't test postgres and mysql but they should shring aswell for ~30%

Are you fine with using alpine images?

**Comment by pglombardo** [comment]
> Are you fine with using alpine images?

Let's leave that for later and do smaller changes more slowly to see if anything breaks.  It's a good idea though to do later on if nothing blows up...

I'll test out these builds locally today and post back soon.

**Comment by sirux88** [comment]
> Let's leave that for later and do smaller changes more slowly to see if anything breaks. It's a good idea though to do later on if nothing blows up...
> 
> I'll test out these builds locally today and post back soon.

Fine for me. I'll keep that in mind and will open a new PR when this one got merged.

I marked this PR for review. Should be ready now

**Comment by pglombardo** [comment]
I'll retest and aim to merge this in the next couple days.

**Comment by pglombardo** [comment]
Thanks @sirux88!  This is great work.  I'm going to merge and make a few touch ups to remove older cruft (yarn no longer needed etc..).  After that I'll work on your other PR.

**Comment by sirux88** [comment]
You are welcome. 
Glad to help you a bit with this awesome piece of software

**Comment by pglombardo** [comment]
This was released in [v1.25.0](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.25.0).

**Pull request merged**
