### PR TITLE
DOCKER: Improve docker build action on github

### PR DESCRIPTION
**Pull request by sirux88**
## Description
This PR includes:
- Fixes not working dispatch option build (a dollar sign was missing)
- Refactor the docker build action to use matrix build which dedupes copied jobs
- Adds an option to not push to docker hub when running build action manually.
  This could be useful while testing docker build changes

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've written tests (if applicable) for all new methods and classes that I created. (`rake test`)
- [ ] I've added documentation as necessary so users can easily use and understand this feature/fix.

### CODE REVIEW

**Comment by pglombardo** [comment]
Nice PR @sirux88!  That's a good improvement to simplify things too.  My laptop died so this might not get merged until next week.

**Comment by pglombardo** [comment]
Hey @sirux88 - it took way longer for the new Mac to arrive than I wanted but I'm back.  I'll merge and test out a new release soon.  Thanks!

**Comment by pglombardo** [comment]
Building now in

https://github.com/pglombardo/PasswordPusher/releases/tag/v1.26.6
https://github.com/pglombardo/PasswordPusher/actions/runs/4356581000

**Comment by sirux88** [comment]
Happy to see you back online @pglombardo 
Seems like builds went well and were uploaded to docker hub aswell

**Pull request merged**
