### PR TITLE
Add versioning

### PR DESCRIPTION
**Pull request by sirux88**
### This PR adds:
1) the gem [version](https://github.com/stouset/version) to the application
This gem adds a file "VERSION" on project root. This file only includes `semver` version string.
In ruby code it can be used by writing `Version.current`. It needs `require 'Version'`
2) The Version on the web frontend next to copyright statement 
image
3) Additionally the version is written to console while app starting:
image

### Some additional info on the gem:

The bumping can be done by using a rake task The baseline task `rake version:bump` without addition will bump revision. 
Possible additions would be `:major`, `:minor`, `:revision` `:pre`. For more info see the link above on 1)

The rake task is currently configured to do a seperate bumping commit but to not add tags to github repo.

Bumping by only changing the contents of `VERSION` is a valid option aswell.

## Related Issue
https://github.com/pglombardo/PasswordPusher/issues/1462

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [X] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've written tests (if applicable) for all new methods and classes that I created. (`rake test`)
- [ ] I've added documentation as necessary so users can easily use and understand this feature/fix.

### CODE REVIEW

**Comment by MindTooth** [comment]
How is the stance on disclosing the version if/when a security breach is present?  Not sure if the version is disclosed other places as well.

**Comment by pglombardo** [comment]
I don't think there are any security benefits in hiding it.  If people request it enough, we could have it on by default and have an off option in `settings.yml`.  For now, let's just put it _without_ the option to disable it and see what response we get.

**Comment by sirux88** [comment]
If anyone wants to do some harm by using a security breach hiding the version on the web interface will not make the person stop doing/trying.

Therefore hiding would only add some subjective security. 

So I agree with @pglombardo.

**Comment by sirux88** [comment]
I'm fine on how this works currently @pglombardo. 
Maybe you could review and test this

**Comment by pglombardo** [comment]
Tried it out, bumped a version and it looks slick.  Thanks @sirux88!  I'll merge run a few more tests, bumps the version and release now.

**Pull request merged**
