### PR TITLE
Slack Integration

### PR DESCRIPTION
**Pull request by pglombardo**
First try at an integration against a test site.

schermata 2018-02-07 alle 11 03 11
schermata 2018-02-07 alle 11 03 00

### CODE REVIEW

**Comment by alexandrezia** [comment]
Just to let my feedback here, I'm using this branch, integrated with Slack, working fine.

**Comment by pglombardo** [comment]
Cool thanks for confirming.  I need to merge this soon.

**Comment by pglombardo** [comment]
This has been released to pwpush.com but not announced yet.  I need to write some docs and put a link on twitter etc..

But if you know how already, you can start using this on pwpush.com or your local instances by updating.

**Comment by dalenoe** [comment]
Nice..

I need to get back and try this software again, lots of activity in the repo. 👍

**Comment by elfalem** [comment]
Where can I find instructions to install this integration?

**Comment by pglombardo** [comment]
I'm behind on writing docs for this feature (and other tasks) - way to busy lately - my apologies.

I just threw together some barebones docs here: https://github.com/pglombardo/PasswordPusher/wiki/PasswordPusher-&-Slack:-Custom-Slash-Command

**Pull request merged**
