### PR TITLE
Update Configuration.md

### PR DESCRIPTION
**Pull request by kayvanaarssen**
Fixed PWP_PRECOMPILE typo to PWP__PRECOMPILE

### CODE REVIEW

**Comment by pglombardo** [comment]
This one is "technically" correct currently (but confusing).

Most of the environment variables use the double underscore as they are part of the Settings system in the application.  `PWP_PRECOMPILE` is used in [entrypoint.sh](https://github.com/pglombardo/PasswordPusher/blob/master/containers/docker/pwpush-ephemeral/entrypoint.sh#L9) for the containers.

**Comment by kayvanaarssen** [comment]
Right, when I used it in my .env file... The docker container kept restarting.
Adding the second _ it worked...

**Comment by pglombardo** [comment]
I think that's a separate issue.  When you have `PWP_PRECOMPILE` set (with one underscore) it re-compiles all of the assets for the new theme.  This can take 30-90 seconds depending on the system unfortunately which is why I made it optional.

If you're using K8s (and some others), there is a container boot response time - if set too low it automatically tries to restart the container when it reality it was taking longer to boot to re-compile assets.

**Comment by kayvanaarssen** [comment]
Right, thanks. Indeed its running on a dedicated VM only one core 2GB RAM since uploading is going straight to S3 it has no load on the server. Very impressed since its working now as expected, with the performance. Good job!

Did also find the custom mysql login part to set in the .evn file.
Documentation can be worked on a bit I think :-D

**Pull request closed without merging**
