### PR TITLE
DOCKER: removed deprecated docker containers and references

### PR DESCRIPTION
**Pull request by sirux88**
## Description
This PR should contain all the necessary steps to remove the deprecated docker container images with its references from the repo. 

This is related to the introduction of the new unified/universal docker container image (PR see below)

Aswell this is meant to be WIP until support for these deprecated images will be dropped.

#
## Related Issue
#1369 

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [X] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've written tests (if applicable) for all new methods and classes that I created. (`rake test`)
- [ ] I've added documentation as necessary so users can easily use and understand this feature/fix.

### CODE REVIEW

**Comment by sirux88** [comment]
Shall we aswell move the content of `containers/docker/pwpush` one level up to directly into `containers/docker` @pglombardo?
There is no need to have it in a sub directory any longer.

**Comment by MindTooth** [comment]
Containters ~= Docker.

I'm where I prefer the `Dockerfile` in root if it's just building said project.

Then rename `containers/` to `examples/` or `deploy/`. 🤷🏻‍♂️

Just to chime in. 😅

**Comment by pglombardo** [comment]
> Shall we aswell move the content of containers/docker/pwpush one level up to directly into containers/docker

Sure - that makes sense.

Also I believe I deleted RELEASE.md yesterday - that file is no longer needed.

I like having Dockerfile in the root directory too but we also have the entrypoint.sh, docker compose files and the README so better off in a subdirectory for now.

**Comment by pglombardo** [comment]
Also I pushed 764c0efd05cf13cd7e28b0170aa4d5c15c28ac5a to master to update the entrypoint.sh link to documentation.  You probably want to update this branch to sync with master when you can.

**Comment by sirux88** [comment]
> > Shall we aswell move the content of containers/docker/pwpush one level up to directly into containers/docker
> 
> Sure - that makes sense.
> 
> Also I believe I deleted RELEASE.md yesterday - that file is no longer needed.
> 
> I like having Dockerfile in the root directory too but we also have the entrypoint.sh, docker compose files and the README so better off in a subdirectory for now.

I agree. Lets keep it in this sub dir for now.

**Comment by sirux88** [comment]
> Also I pushed [764c0ef](https://github.com/pglombardo/PasswordPusher/commit/764c0efd05cf13cd7e28b0170aa4d5c15c28ac5a) to master to update the entrypoint.sh link to documentation. You probably want to update this branch to sync with master when you can.

I'll try to keep this draft in sync to master until support for the obsolete containers finally will be dropped

**Comment by pglombardo** [comment]
> > Shall we aswell move the content of containers/docker/pwpush one level up to directly into containers/docker
>
> I like having Dockerfile in the root directory too but we also have the entrypoint.sh, docker compose files and the README so better off in a subdirectory for now.

This was in response to @MindTooth.  @sirux88 If you want to move the files up to `containers/docker` that makes sense to me.

> I also scanned the wiki for necessary changes concering this draft.
> As far as I can tell it's only this [paragraph](https://github.com/pglombardo/PasswordPusher/wiki/Switch-to-Another-> > > Backend-Database#overview) that is outdated.
> 
> But since it is not directly related to this PR it can be updated anyway.
> If it's ok for you I'll update it by myself

By all means, feel free/thanks.

**Comment by sirux88** [comment]
> ~This was in response to @MindTooth. @sirux88 If you want to move the files up to `containers/docker` that makes sense to me.~
> 
> Now I see you already did - perfect.

What I wrote was a bit confusing. I just wanted to agree to your suggestion.


> > I also scanned the wiki for necessary changes concering this draft.
> > As far as I can tell it's only this [paragraph]([https://github.com/pglombardo/PasswordPusher/wiki/Switch-to-Another->](https://github.com/pglombardo/PasswordPusher/wiki/Switch-to-Another-%3E) > > Backend-Database#overview) that is outdated.
> > But since it is not directly related to this PR it can be updated anyway.
> > If it's ok for you I'll update it by myself
> 
> By all means, feel free/thanks.

Done.

**Comment by pglombardo** [comment]
Hey @sirux88 - whenever you can let's merge this.  ...time to clean up and get rid of the old stuff.

**Comment by sirux88** [comment]
@pglombardo: I rebased to current master. Aswell I rescanned for any obsolete references but didn't find any.

So this should be ready for merging

**Comment by sirux88** [comment]
@pglombardo: Maybe we should change the depracation notice like [this one](https://github.com/pglombardo/PasswordPusher/blob/e9d83ea6ea4360f41fa388579bcd7a42a84ce140/containers/docker/pwpush-ephemeral/Dockerfile#L9C1-L20C1) for the old images into a end of support notice build, let the images be built and pushed to docker hub.

Let me know if you want to do this. I'll throw another PR then.

Afterwards we could merge this PR.

**Comment by pglombardo** [comment]
Ah good point - that's a great idea.  Let's do that by all means.

**Comment by sirux88** [comment]
should be ready for merge now @pglombardo

**Comment by pglombardo** [comment]
And with that merge, it concludes the final move to the universal container.  Thanks to both of you for the input and contributions to get to this point!

**Pull request merged**
